// copies the shared explain spec inputs into a generated ts module, the
// web twin of the cli's include_str!. edit shared/prompts/, never the
// generated file; predev/prebuild/pretest rerun this so drift is impossible.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const shared = resolve(here, "../../shared/prompts");
const out = resolve(here, "../lib/explain/shared.gen.ts");

const excludeTxt = readFileSync(resolve(shared, "exclude.txt"), "utf8");
const explainTemplate = readFileSync(resolve(shared, "explain.md"), "utf8");

writeFileSync(
  out,
  `// generated by scripts/sync-shared.mjs from shared/prompts/, do not edit
export const excludeTxt = ${JSON.stringify(excludeTxt)};
export const explainTemplate = ${JSON.stringify(explainTemplate)};
`
);
console.log("sync-shared: wrote lib/explain/shared.gen.ts");
